### ISSUE TITLE
pip won't install lensetools

### ISSUE THREAD

**Issue by srebre** [apetri/LensTools#4]
I'm using Anaconda Python 3 version and can't seem to install lenstools with pip. The output I get is:

```
matej@Dream ~/source $ pip install lenstools
Collecting lenstools
  Using cached lenstools-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6pv3kv1r/lenstools/setup.py", line 153, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6pv3kv1r/lenstools/
```

**Comment by srebre** [comment]
[This](https://github.com/aplpy/aplpy/commit/fddb0a60551707a0f5eeb3b66924d4d295ade8b2) might solve it.

**Comment by apetri** [comment]
Hi Matej, I am aware that the master branch is not compatible with python3 (I originally worked in the python2.7 environment); I patched a version for python3 but did not release it yet. If you really want to use python3, then install manually the fastpm branch (which has FastPM support and is patched for python3); let me know how it goes!
